name: game_of_life
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

  rle_parser:
    path: packages/rle_parser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shader/game_of_life_simulate.frag

  assets:
    - assets/json/
