{
  "sksl": {
    "entrypoint": "game_of_life_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_size;\nuniform vec4 u_backGround;\nuniform vec2 u_gridSize;\nuniform vec2 u_list[5];\n\nvec4 FragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 pixel = FLT_flutter_local_FlutterFragCoord() / u_size;\n    float gridX = u_gridSize.x;\n    float gridY = u_gridSize.y;\n    vec2 gridPos = floor(pixel * vec2(gridX, gridY));\n    bool contains = false;\n    for (int i = 0; i < 5; i++)\n    {\n        if (all(equal(u_list[i], gridPos)))\n        {\n            contains = true;\n            break;\n        }\n    }\n    if (contains)\n    {\n        FragColor = vec4(0.533299982547760009765625, 0.705900013446807861328125, 1.0, 1.0);\n    }\n    else\n    {\n        FragColor = u_backGround;\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return FragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_backGround",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_gridSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 5,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "u_list",
        "rows": 2,
        "type": 10
      }
    ]
  }
}